#ifndef SDL3PP_CONFIG_HH
#define SDL3PP_CONFIG_HH

#define SDL3PP_MAJOR_VERSION 
#define SDL3PP_MINOR_VERSION 
#define SDL3PP_PATCH_VERSION 

#define SDL3PP_VERSION ""

#define SDL3PP_WITH_IMAGE
#define SDL3PP_WITH_TTF
#define SDL3PP_WITH_MIXER

#endif
